/*
 * ============================================================
 * User.java — Data Model / DTO (Data Transfer Object)
 * ============================================================
 * This class represents a USER in our system. It defines:
 *   - What data a user has (id, name, email, role)
 *   - Validation rules (name can't be blank, email must be valid, etc.)
 *
 * WHAT IS A MODEL/DTO?
 * A model (or DTO) is a plain Java class that holds data.
 * When someone sends a POST request to create a user, the JSON
 * body gets converted INTO this object. When we return a user,
 * this object gets converted INTO JSON.
 *
 * JSON ←→ User object conversion is handled automatically by
 * Jackson (included in spring-boot-starter-web).
 *
 * WHAT ARE VALIDATION ANNOTATIONS?
 * Annotations like @NotBlank and @Email are from Jakarta Validation.
 * They automatically check incoming data and reject invalid requests
 * with a 400 Bad Request response (handled by our GlobalExceptionHandler).
 * ============================================================
 */
package com.contracttest.provider.model;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Represents a User entity in the system.
 *
 * Used for:
 *   - Incoming request bodies (POST /api/users, PUT /api/users/{id})
 *   - Outgoing response bodies (GET /api/users, GET /api/users/{id})
 */
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by UserService when creating a new user.
     * Not required in POST requests (server assigns it).
     */
    private Long id;

    /**
     * User's full name.
     *
     * @NotBlank: Must not be null AND must contain at least one non-whitespace character.
     *            Example: "" (blank) → INVALID, "  " (spaces) → INVALID, "John" → VALID
     *
     * @Size: String length must be between min and max (inclusive).
     *        This prevents extremely short or long names.
     */
    @NotBlank(message = "Name is required and cannot be blank")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    /**
     * User's email address.
     *
     * @NotBlank: Must not be empty (email is required).
     * @Email: Must be a valid email format (e.g., user@example.com).
     *         Invalid examples: "notanemail", "@missing.com", "spaces in@email.com"
     */
    @NotBlank(message = "Email is required and cannot be blank")
    @Email(message = "Email must be a valid email address")
    private String email;

    /**
     * User's role in the system.
     * Examples: "ADMIN", "USER", "MANAGER"
     *
     * @NotBlank: Role is required.
     */
    @NotBlank(message = "Role is required and cannot be blank")
    private String role;

    // ============================================================
    // CONSTRUCTORS
    // ============================================================
    // Java classes need constructors to create objects.
    // We provide two: a no-args constructor (required by Jackson
    // for JSON deserialization) and a full constructor for convenience.
    // ============================================================

    /**
     * No-argument constructor.
     * Required by Jackson (JSON library) for deserialization.
     * When a JSON request body comes in, Jackson creates an empty
     * User object and then sets each field using the setters.
     */
    public User() {
    }

    /**
     * Full constructor for creating a User with all fields.
     * Used in our service layer and tests for convenience.
     *
     * @param id    Unique identifier
     * @param name  User's full name
     * @param email User's email address
     * @param role  User's role (ADMIN, USER, MANAGER)
     */
    public User(Long id, String name, String email, String role) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.role = role;
    }

    // ============================================================
    // GETTERS AND SETTERS
    // ============================================================
    // Getters and setters follow the JavaBean convention.
    // Jackson uses these to read/write JSON properties.
    // For a field "name", Jackson looks for getName() and setName().
    // ============================================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    // ============================================================
    // toString() — For logging and debugging
    // ============================================================

    @Override
    public String toString() {
        return "User{id=" + id + ", name='" + name + "', email='" + email + "', role='" + role + "'}";
    }
}
